# Generated by Django 3.2.3 on 2021-06-25 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subsidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0.0)),
                ('descripcion', models.CharField(default='Sin informacion', max_length=300)),
                ('duracion', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(max_length=12, unique=True, verbose_name='dui')),
                ('dire', models.CharField(default='Sin Informacion', max_length=200)),
                ('telefono', models.CharField(default='00000000', max_length=8)),
                ('depar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasubsidio.departamento')),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasubsidio.municipio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dui'],
            },
        ),
        migrations.CreateModel(
            name='aplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasubsidio.documento')),
                ('subsidio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasubsidio.subsidios')),
            ],
        ),
    ]
