# Generated by Django 3.2.3 on 2021-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasubsidio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplica',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
