# Generated by Django 3.2.3 on 2021-06-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Cuestionario', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('alcance', models.BooleanField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='item_pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['contenido'],
            },
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopreguntas', models.CharField(choices=[('CH', 'checkbox'), ('TX', 'text'), ('RD', 'radio'), ('NUM', 'number'), ('IMG', 'file')], max_length=20)),
                ('texto_pregunta', models.CharField(max_length=300)),
                ('cuestionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
            ],
            options={
                'ordering': ['texto_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='registrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
                ('item_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.item_pregunta')),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.pregunta')),
                ('registros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.registro')),
            ],
            options={
                'ordering': ['registros'],
            },
        ),
        migrations.AddField(
            model_name='item_pregunta',
            name='preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.pregunta'),
        ),
    ]
