# Generated by Django 3.2.3 on 2021-06-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='cuestionarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestio', to='cuestionarios.cuestionario'),
        ),
    ]
