# Generated by Django 3.2.3 on 2021-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_rename_cuestionarios_pregunta_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='guardado',
            field=models.CharField(default='Sin informacion', max_length=200),
        ),
    ]
