# Generated by Django 3.2.3 on 2021-06-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_registrado_guardado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipopreguntas',
            field=models.CharField(choices=[('CH', 'checkbox'), ('TX', 'text'), ('NUM', 'number')], max_length=20),
        ),
    ]
